package damas.entity;
// Generated 28/02/2020 17:59:10 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Partida generated by hbm2java
 */
public class Partida  implements java.io.Serializable {


     private Integer numeroPartida;
     private Date data;
     private int numeroMoviments;
     private String quiHaGuanyat;

    public Partida() {
    }

    public Partida(Date data, int numeroMoviments, String quiHaGuanyat) {
       this.data = data;
       this.numeroMoviments = numeroMoviments;
       this.quiHaGuanyat = quiHaGuanyat;
    }
   
    public Integer getNumeroPartida() {
        return this.numeroPartida;
    }
    
    public void setNumeroPartida(Integer numeroPartida) {
        this.numeroPartida = numeroPartida;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public int getNumeroMoviments() {
        return this.numeroMoviments;
    }
    
    public void setNumeroMoviments(int numeroMoviments) {
        this.numeroMoviments = numeroMoviments;
    }
    public String getQuiHaGuanyat() {
        return this.quiHaGuanyat;
    }
    
    public void setQuiHaGuanyat(String quiHaGuanyat) {
        this.quiHaGuanyat = quiHaGuanyat;
    }
}


